# ---------------------------------------------------------------------------
# actuated.yaml — Actuated traffic signal timing (2025)
# ---------------------------------------------------------------------------
# Purpose
#   Tunables for the actuated controller.
#   The controller enforces a minimum green, allows dynamic extensions up to a
#   maximum green based on detector gaps, and uses a fixed yellow interval.
#
# Units
#   All durations are expressed in seconds.
#
# Invariants
#   - green_min > 0
#   - green_max > 0
#   - yellow_fix > 0
#   - green_min < green_max
#   - green_min <= green_duration <= green_max
#
# Notes
#   - green_duration: nominal/initial green budget before any extension logic.
#   - Extensions (gap-out) may increase the active green but never beyond green_max.
#   - The change interval between phases is fixed by yellow_fix.
# ---------------------------------------------------------------------------

green_duration: 42.0  # seconds; nominal green before extensions
green_min: 15.0       # seconds; enforced minimum green service time
green_max: 50.0       # seconds; hard cap for any extension
yellow_fix: 3.0       # seconds; fixed yellow (amber) between phases