# ---------------------------------------------------------------------------
# fuzzy.yaml — Fuzzy controller knowledge base (2025)
# ---------------------------------------------------------------------------
# Purpose
#   Knowledge base for the fuzzy traffic signal controller.
#   It defines linguistic variables (with their linguistic levels and ranges)
#   and the rule base mapping inputs → output.
#
# Conventions
#   - All names are lowercase with underscores.
#   - 'functions' declares the fuzzy variables:
#       * 'arrival'  : input — normalized arrival-rate (0.0–1.0)
#       * 'vehicles' : input — queue length (vehicles)
#       * 'green'    : output — green duration (seconds)
#   - lmin/lmax specify the variable universe (crisp range before fuzzification).
#   - Rule format (triplet): [vehicles_level, arrival_level, green_level]
#     i.e., IF vehicles IS <x> AND arrival IS <y> THEN green IS <z>.
# ---------------------------------------------------------------------------

functions:
  arrival:
    # Input — normalized arrival rate (0.0–1.0). Unitless.
    levels: [very_slow, slow, medium, moderate, fast]
    lmin: 0.0
    lmax: 1.0

  green:
    # Output — green time (seconds). Defuzzified result will be within [lmin, lmax].
    levels: [very_short, short, normal, long, very_long]
    lmin: 15
    lmax: 36

  vehicles:
    # Input — queue length (vehicles) at detection zone.
    levels: [very_few, few, normal, many, very_many]
    lmin: 3
    lmax: 13

# ---------------------------------------------------------------------------
# Rule base
#   Triplets in the form:
#     - [vehicles_level, arrival_level, green_level]
#   Grouped by 'vehicles' to improve readability.
# ---------------------------------------------------------------------------
rules:
  # --- vehicles: very_few ---------------------------------------------------
  - [very_few, very_slow, very_short]
  - [very_few, slow,      very_short]
  - [very_few, medium,    very_short]
  - [very_few, moderate,  short]
  - [very_few, fast,      short]

  # --- vehicles: few --------------------------------------------------------
  - [few,      very_slow, very_short]
  - [few,      slow,      short]
  - [few,      medium,    short]
  - [few,      moderate,  normal]
  - [few,      fast,      normal]

  # --- vehicles: normal -----------------------------------------------------
  - [normal,   very_slow, short]
  - [normal,   slow,      short]
  - [normal,   medium,    normal]
  - [normal,   moderate,  long]
  - [normal,   fast,      long]

  # --- vehicles: many -------------------------------------------------------
  - [many,     very_slow, normal]
  - [many,     slow,      normal]
  - [many,     medium,    long]
  - [many,     moderate,  long]
  - [many,     fast,      very_long]

  # --- vehicles: very_many --------------------------------------------------
  - [very_many, very_slow, long]
  - [very_many, slow,      long]
  - [very_many, medium,    very_long]
  - [very_many, moderate,  very_long]
  - [very_many, fast,      very_long]
