# ---------------------------------------------------------------------------
# static.yaml — Fixed-time (static) traffic signal timing (2025)
# ---------------------------------------------------------------------------
# Purpose
#   Parameters for the fixed-time controller.
#   The controller applies constant green and yellow intervals with no actuation.
#
# Units
#   All durations are expressed in seconds (integers).
#
# Invariants
#   - green_fix  > 0
#   - yellow_fix > 0
#
# Notes
#   - green_fix  : fixed green duration per phase (no extensions).
#   - yellow_fix : fixed yellow (amber) change interval between phases.
# ---------------------------------------------------------------------------

green_fix: 42   # seconds; fixed green duration
yellow_fix: 3   # seconds; fixed yellow interval